isc: xcode arguments array
Seagate/cortx-motr-apps pull request #30
Opened 2021-06-07 22:09 UTC by andriytk

Encode/decode arguments array for ISC with xcode.

2021-06-08 16:16 UTC, siningwuseagate approved these changes

2021-06-09 13:58 UTC, chumakd requested changes

2021-06-09 13:58 UTC, chumakd commented on Makefile
> +CXXXML_CFLAGS := $(filter-out $(CXXXML_UNSUPPORTED_CFLAGS), $(CFLAGS)) -iquote'/home/ant/motr' -include'config.h'
hardcoded user-specific path `/home/ant`

2021-06-09 14:10 UTC, andriytk commented on Makefile
> +CXXXML_CFLAGS := $(filter-out $(CXXXML_UNSUPPORTED_CFLAGS), $(CFLAGS)) -iquote'/home/ant/motr' -include'config.h'
Oh, good spot!

2021-06-09 15:08 UTC, andriytk commented on Makefile
> +CXXXML_CFLAGS := $(filter-out $(CXXXML_UNSUPPORTED_CFLAGS), $(CFLAGS)) -iquote'/home/ant/motr' -include'config.h'
Fixed.

2021-06-09 16:30 UTC, merged